/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedEasyorderRouteImport } from './routes/_authenticated/easyorder'
import { Route as AuthenticatedLohnRouteImport } from './routes/_authenticated/lohn'
import { Route as AuthenticatedPasswortAendernRouteImport } from './routes/_authenticated/passwort-aendern'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as DisplayLocationIdRouteImport } from './routes/display.$locationId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAufgabenRouteImport } from './routes/_authenticated/admin/aufgaben'
import { Route as AuthenticatedAdminAufgabenDisplayRouteImport } from './routes/_authenticated/admin/aufgaben-display'
import { Route as AuthenticatedAdminBankkontoRouteImport } from './routes/_authenticated/admin/bankkonto'
import { Route as AuthenticatedAdminBestellungRouteImport } from './routes/_authenticated/admin/bestellung'
import { Route as AuthenticatedAdminBilanzRouteImport } from './routes/_authenticated/admin/bilanz'
import { Route as AuthenticatedAdminBwaRouteImport } from './routes/_authenticated/admin/bwa'
import { Route as AuthenticatedAdminConfigCheckRouteImport } from './routes/_authenticated/admin/config-check'
import { Route as AuthenticatedAdminDienstplanRouteImport } from './routes/_authenticated/admin/dienstplan'
import { Route as AuthenticatedAdminDokumenteRouteImport } from './routes/_authenticated/admin/dokumente'
import { Route as AuthenticatedAdminEinstellungenRouteImport } from './routes/_authenticated/admin/einstellungen'
import { Route as AuthenticatedAdminFragCocoRouteImport } from './routes/_authenticated/admin/frag-coco'
import { Route as AuthenticatedAdminImpersonateRouteImport } from './routes/_authenticated/admin/impersonate'
import { Route as AuthenticatedAdminImportZuordnungenRouteImport } from './routes/_authenticated/admin/import-zuordnungen'
import { Route as AuthenticatedAdminKasseRouteImport } from './routes/_authenticated/admin/kasse'
import { Route as AuthenticatedAdminKasseSaldoRouteImport } from './routes/_authenticated/admin/kasse-saldo'
import { Route as AuthenticatedAdminLocationsRouteImport } from './routes/_authenticated/admin/locations'
import { Route as AuthenticatedAdminLohnVerteilungRouteImport } from './routes/_authenticated/admin/lohn-verteilung'
import { Route as AuthenticatedAdminMigrationRouteImport } from './routes/_authenticated/admin/migration'
import { Route as AuthenticatedAdminPersonalAntraegeRouteImport } from './routes/_authenticated/admin/personal-antraege'
import { Route as AuthenticatedAdminPosRennerPennerRouteImport } from './routes/_authenticated/admin/pos-renner-penner'
import { Route as AuthenticatedAdminPosStundenberichtRouteImport } from './routes/_authenticated/admin/pos-stundenbericht'
import { Route as AuthenticatedAdminPosVerkaufRouteImport } from './routes/_authenticated/admin/pos-verkauf'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminStandortzeitenRouteImport } from './routes/_authenticated/admin/standortzeiten'
import { Route as AuthenticatedAdminStatistikRouteImport } from './routes/_authenticated/admin/statistik'
import { Route as AuthenticatedAdminTrinkgeldRestRouteImport } from './routes/_authenticated/admin/trinkgeld-rest'
import { Route as AuthenticatedAdminUrlaubRouteImport } from './routes/_authenticated/admin/urlaub'
import { Route as AuthenticatedAdminVerkaufsartikelRouteImport } from './routes/_authenticated/admin/verkaufsartikel'
import { Route as AuthenticatedAdminWeinRouteImport } from './routes/_authenticated/admin/wein'
import { Route as AuthenticatedAdminWeinQuizRouteImport } from './routes/_authenticated/admin/wein-quiz'
import { Route as AuthenticatedAdminZeitUebersichtRouteImport } from './routes/_authenticated/admin/zeit-uebersicht'
import { Route as AuthenticatedZeitIndexRouteImport } from './routes/_authenticated/zeit/index'
import { Route as AuthenticatedZeitAbrechnungRouteImport } from './routes/_authenticated/zeit/abrechnung'
import { Route as AuthenticatedZeitAufgabenRouteImport } from './routes/_authenticated/zeit/aufgaben'
import { Route as AuthenticatedZeitKalenderRouteImport } from './routes/_authenticated/zeit/kalender'
import { Route as AuthenticatedZeitSchichtenRouteImport } from './routes/_authenticated/zeit/schichten'
import { Route as AuthenticatedZeitStempelnRouteImport } from './routes/_authenticated/zeit/stempeln'
import { Route as AuthenticatedZeitStundenRouteImport } from './routes/_authenticated/zeit/stunden'
import { Route as AuthenticatedZeitTauschRouteImport } from './routes/_authenticated/zeit/tausch'
import { Route as AuthenticatedZeitUrlaubRouteImport } from './routes/_authenticated/zeit/urlaub'
import { Route as AuthenticatedZeitWuenscheRouteImport } from './routes/_authenticated/zeit/wuensche'
import { Route as ApiExportDownloadRouteImport } from './routes/api/export/download'
import { Route as AuthenticatedAdminBestellungIndexRouteImport } from './routes/_authenticated/admin/bestellung.index'
import { Route as AuthenticatedAdminBestellungBestellungenRouteImport } from './routes/_authenticated/admin/bestellung.bestellungen'
import { Route as AuthenticatedAdminBestellungInventurRouteImport } from './routes/_authenticated/admin/bestellung.inventur'
import { Route as AuthenticatedAdminBestellungLieferantenRouteImport } from './routes/_authenticated/admin/bestellung.lieferanten'
import { Route as AuthenticatedAdminBestellungUnzugeordnetRouteImport } from './routes/_authenticated/admin/bestellung.unzugeordnet'
import { Route as AuthenticatedAdminEinstellungenIndexRouteImport } from './routes/_authenticated/admin/einstellungen.index'
import { Route as AuthenticatedAdminEinstellungenEasyorderVerwaltungRouteImport } from './routes/_authenticated/admin/einstellungen.easyorder-verwaltung'
import { Route as AuthenticatedAdminEinstellungenVeranstaltungenRouteImport } from './routes/_authenticated/admin/einstellungen.veranstaltungen'
import { Route as AuthenticatedAdminStaffIndexRouteImport } from './routes/_authenticated/admin/staff.index'
import { Route as AuthenticatedAdminStaffStaffIdRouteImport } from './routes/_authenticated/admin/staff.$staffId'
import { Route as AuthenticatedAdminStaffNewRouteImport } from './routes/_authenticated/admin/staff.new'
import { Route as ApiPublicBankSyncSpiceryRouteImport } from './routes/api/public/bank/sync-spicery'
import { Route as ApiPublicCalendarTokenRouteImport } from './routes/api/public/calendar.$token'
import { Route as ApiPublicDisplayLocationIdRouteImport } from './routes/api/public/display.$locationId'
import { Route as ApiPublicMailersendWebhookRouteImport } from './routes/api/public/mailersend/webhook'
import { Route as ApiPublicTelegramDailyReportRouteImport } from './routes/api/public/telegram/daily-report'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTrmnlDienstplanTokenRouteImport } from './routes/api/public/trmnl-dienstplan.$token'
import { Route as ApiPublicTrmnlPlanungstafelTokenRouteImport } from './routes/api/public/trmnl-planungstafel.$token'
import { Route as ApiPublicTrmnlTasksTokenRouteImport } from './routes/api/public/trmnl-tasks.$token'
import { Route as ApiPublicWeatherSyncRouteImport } from './routes/api/public/weather/sync'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEasyorderRoute = AuthenticatedEasyorderRouteImport.update({
  id: '/easyorder',
  path: '/easyorder',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLohnRoute = AuthenticatedLohnRouteImport.update({
  id: '/lohn',
  path: '/lohn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPasswortAendernRoute =
  AuthenticatedPasswortAendernRouteImport.update({
    id: '/passwort-aendern',
    path: '/passwort-aendern',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DisplayLocationIdRoute = DisplayLocationIdRouteImport.update({
  id: '/display/$locationId',
  path: '/display/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAufgabenRoute =
  AuthenticatedAdminAufgabenRouteImport.update({
    id: '/aufgaben',
    path: '/aufgaben',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAufgabenDisplayRoute =
  AuthenticatedAdminAufgabenDisplayRouteImport.update({
    id: '/aufgaben-display',
    path: '/aufgaben-display',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBankkontoRoute =
  AuthenticatedAdminBankkontoRouteImport.update({
    id: '/bankkonto',
    path: '/bankkonto',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBestellungRoute =
  AuthenticatedAdminBestellungRouteImport.update({
    id: '/bestellung',
    path: '/bestellung',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBilanzRoute =
  AuthenticatedAdminBilanzRouteImport.update({
    id: '/bilanz',
    path: '/bilanz',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBwaRoute = AuthenticatedAdminBwaRouteImport.update({
  id: '/bwa',
  path: '/bwa',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminConfigCheckRoute =
  AuthenticatedAdminConfigCheckRouteImport.update({
    id: '/config-check',
    path: '/config-check',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDienstplanRoute =
  AuthenticatedAdminDienstplanRouteImport.update({
    id: '/dienstplan',
    path: '/dienstplan',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDokumenteRoute =
  AuthenticatedAdminDokumenteRouteImport.update({
    id: '/dokumente',
    path: '/dokumente',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEinstellungenRoute =
  AuthenticatedAdminEinstellungenRouteImport.update({
    id: '/einstellungen',
    path: '/einstellungen',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFragCocoRoute =
  AuthenticatedAdminFragCocoRouteImport.update({
    id: '/frag-coco',
    path: '/frag-coco',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImpersonateRoute =
  AuthenticatedAdminImpersonateRouteImport.update({
    id: '/impersonate',
    path: '/impersonate',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminImportZuordnungenRoute =
  AuthenticatedAdminImportZuordnungenRouteImport.update({
    id: '/import-zuordnungen',
    path: '/import-zuordnungen',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminKasseRoute = AuthenticatedAdminKasseRouteImport.update({
  id: '/kasse',
  path: '/kasse',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminKasseSaldoRoute =
  AuthenticatedAdminKasseSaldoRouteImport.update({
    id: '/kasse-saldo',
    path: '/kasse-saldo',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLocationsRoute =
  AuthenticatedAdminLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLohnVerteilungRoute =
  AuthenticatedAdminLohnVerteilungRouteImport.update({
    id: '/lohn-verteilung',
    path: '/lohn-verteilung',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMigrationRoute =
  AuthenticatedAdminMigrationRouteImport.update({
    id: '/migration',
    path: '/migration',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPersonalAntraegeRoute =
  AuthenticatedAdminPersonalAntraegeRouteImport.update({
    id: '/personal-antraege',
    path: '/personal-antraege',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPosRennerPennerRoute =
  AuthenticatedAdminPosRennerPennerRouteImport.update({
    id: '/pos-renner-penner',
    path: '/pos-renner-penner',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPosStundenberichtRoute =
  AuthenticatedAdminPosStundenberichtRouteImport.update({
    id: '/pos-stundenbericht',
    path: '/pos-stundenbericht',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPosVerkaufRoute =
  AuthenticatedAdminPosVerkaufRouteImport.update({
    id: '/pos-verkauf',
    path: '/pos-verkauf',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStandortzeitenRoute =
  AuthenticatedAdminStandortzeitenRouteImport.update({
    id: '/standortzeiten',
    path: '/standortzeiten',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStatistikRoute =
  AuthenticatedAdminStatistikRouteImport.update({
    id: '/statistik',
    path: '/statistik',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTrinkgeldRestRoute =
  AuthenticatedAdminTrinkgeldRestRouteImport.update({
    id: '/trinkgeld-rest',
    path: '/trinkgeld-rest',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUrlaubRoute =
  AuthenticatedAdminUrlaubRouteImport.update({
    id: '/urlaub',
    path: '/urlaub',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminVerkaufsartikelRoute =
  AuthenticatedAdminVerkaufsartikelRouteImport.update({
    id: '/verkaufsartikel',
    path: '/verkaufsartikel',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminWeinRoute = AuthenticatedAdminWeinRouteImport.update({
  id: '/wein',
  path: '/wein',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminWeinQuizRoute =
  AuthenticatedAdminWeinQuizRouteImport.update({
    id: '/wein-quiz',
    path: '/wein-quiz',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminZeitUebersichtRoute =
  AuthenticatedAdminZeitUebersichtRouteImport.update({
    id: '/zeit-uebersicht',
    path: '/zeit-uebersicht',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedZeitIndexRoute = AuthenticatedZeitIndexRouteImport.update({
  id: '/zeit/',
  path: '/zeit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZeitAbrechnungRoute =
  AuthenticatedZeitAbrechnungRouteImport.update({
    id: '/zeit/abrechnung',
    path: '/zeit/abrechnung',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeitAufgabenRoute =
  AuthenticatedZeitAufgabenRouteImport.update({
    id: '/zeit/aufgaben',
    path: '/zeit/aufgaben',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeitKalenderRoute =
  AuthenticatedZeitKalenderRouteImport.update({
    id: '/zeit/kalender',
    path: '/zeit/kalender',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeitSchichtenRoute =
  AuthenticatedZeitSchichtenRouteImport.update({
    id: '/zeit/schichten',
    path: '/zeit/schichten',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeitStempelnRoute =
  AuthenticatedZeitStempelnRouteImport.update({
    id: '/zeit/stempeln',
    path: '/zeit/stempeln',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeitStundenRoute =
  AuthenticatedZeitStundenRouteImport.update({
    id: '/zeit/stunden',
    path: '/zeit/stunden',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZeitTauschRoute = AuthenticatedZeitTauschRouteImport.update({
  id: '/zeit/tausch',
  path: '/zeit/tausch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZeitUrlaubRoute = AuthenticatedZeitUrlaubRouteImport.update({
  id: '/zeit/urlaub',
  path: '/zeit/urlaub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedZeitWuenscheRoute =
  AuthenticatedZeitWuenscheRouteImport.update({
    id: '/zeit/wuensche',
    path: '/zeit/wuensche',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiExportDownloadRoute = ApiExportDownloadRouteImport.update({
  id: '/api/export/download',
  path: '/api/export/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminBestellungIndexRoute =
  AuthenticatedAdminBestellungIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminBestellungRoute,
  } as any)
const AuthenticatedAdminBestellungBestellungenRoute =
  AuthenticatedAdminBestellungBestellungenRouteImport.update({
    id: '/bestellungen',
    path: '/bestellungen',
    getParentRoute: () => AuthenticatedAdminBestellungRoute,
  } as any)
const AuthenticatedAdminBestellungInventurRoute =
  AuthenticatedAdminBestellungInventurRouteImport.update({
    id: '/inventur',
    path: '/inventur',
    getParentRoute: () => AuthenticatedAdminBestellungRoute,
  } as any)
const AuthenticatedAdminBestellungLieferantenRoute =
  AuthenticatedAdminBestellungLieferantenRouteImport.update({
    id: '/lieferanten',
    path: '/lieferanten',
    getParentRoute: () => AuthenticatedAdminBestellungRoute,
  } as any)
const AuthenticatedAdminBestellungUnzugeordnetRoute =
  AuthenticatedAdminBestellungUnzugeordnetRouteImport.update({
    id: '/unzugeordnet',
    path: '/unzugeordnet',
    getParentRoute: () => AuthenticatedAdminBestellungRoute,
  } as any)
const AuthenticatedAdminEinstellungenIndexRoute =
  AuthenticatedAdminEinstellungenIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminEinstellungenRoute,
  } as any)
const AuthenticatedAdminEinstellungenEasyorderVerwaltungRoute =
  AuthenticatedAdminEinstellungenEasyorderVerwaltungRouteImport.update({
    id: '/easyorder-verwaltung',
    path: '/easyorder-verwaltung',
    getParentRoute: () => AuthenticatedAdminEinstellungenRoute,
  } as any)
const AuthenticatedAdminEinstellungenVeranstaltungenRoute =
  AuthenticatedAdminEinstellungenVeranstaltungenRouteImport.update({
    id: '/veranstaltungen',
    path: '/veranstaltungen',
    getParentRoute: () => AuthenticatedAdminEinstellungenRoute,
  } as any)
const AuthenticatedAdminStaffIndexRoute =
  AuthenticatedAdminStaffIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminStaffRoute,
  } as any)
const AuthenticatedAdminStaffStaffIdRoute =
  AuthenticatedAdminStaffStaffIdRouteImport.update({
    id: '/$staffId',
    path: '/$staffId',
    getParentRoute: () => AuthenticatedAdminStaffRoute,
  } as any)
const AuthenticatedAdminStaffNewRoute =
  AuthenticatedAdminStaffNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminStaffRoute,
  } as any)
const ApiPublicBankSyncSpiceryRoute =
  ApiPublicBankSyncSpiceryRouteImport.update({
    id: '/api/public/bank/sync-spicery',
    path: '/api/public/bank/sync-spicery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCalendarTokenRoute = ApiPublicCalendarTokenRouteImport.update({
  id: '/api/public/calendar/$token',
  path: '/api/public/calendar/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDisplayLocationIdRoute =
  ApiPublicDisplayLocationIdRouteImport.update({
    id: '/api/public/display/$locationId',
    path: '/api/public/display/$locationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMailersendWebhookRoute =
  ApiPublicMailersendWebhookRouteImport.update({
    id: '/api/public/mailersend/webhook',
    path: '/api/public/mailersend/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramDailyReportRoute =
  ApiPublicTelegramDailyReportRouteImport.update({
    id: '/api/public/telegram/daily-report',
    path: '/api/public/telegram/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrmnlDienstplanTokenRoute =
  ApiPublicTrmnlDienstplanTokenRouteImport.update({
    id: '/api/public/trmnl-dienstplan/$token',
    path: '/api/public/trmnl-dienstplan/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrmnlPlanungstafelTokenRoute =
  ApiPublicTrmnlPlanungstafelTokenRouteImport.update({
    id: '/api/public/trmnl-planungstafel/$token',
    path: '/api/public/trmnl-planungstafel/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrmnlTasksTokenRoute =
  ApiPublicTrmnlTasksTokenRouteImport.update({
    id: '/api/public/trmnl-tasks/$token',
    path: '/api/public/trmnl-tasks/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWeatherSyncRoute = ApiPublicWeatherSyncRouteImport.update({
  id: '/api/public/weather/sync',
  path: '/api/public/weather/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/easyorder': typeof AuthenticatedEasyorderRoute
  '/lohn': typeof AuthenticatedLohnRoute
  '/passwort-aendern': typeof AuthenticatedPasswortAendernRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/display/$locationId': typeof DisplayLocationIdRoute
  '/admin/aufgaben': typeof AuthenticatedAdminAufgabenRoute
  '/admin/aufgaben-display': typeof AuthenticatedAdminAufgabenDisplayRoute
  '/admin/bankkonto': typeof AuthenticatedAdminBankkontoRoute
  '/admin/bestellung': typeof AuthenticatedAdminBestellungRouteWithChildren
  '/admin/bilanz': typeof AuthenticatedAdminBilanzRoute
  '/admin/bwa': typeof AuthenticatedAdminBwaRoute
  '/admin/config-check': typeof AuthenticatedAdminConfigCheckRoute
  '/admin/dienstplan': typeof AuthenticatedAdminDienstplanRoute
  '/admin/dokumente': typeof AuthenticatedAdminDokumenteRoute
  '/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRouteWithChildren
  '/admin/frag-coco': typeof AuthenticatedAdminFragCocoRoute
  '/admin/impersonate': typeof AuthenticatedAdminImpersonateRoute
  '/admin/import-zuordnungen': typeof AuthenticatedAdminImportZuordnungenRoute
  '/admin/kasse': typeof AuthenticatedAdminKasseRoute
  '/admin/kasse-saldo': typeof AuthenticatedAdminKasseSaldoRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/lohn-verteilung': typeof AuthenticatedAdminLohnVerteilungRoute
  '/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/admin/personal-antraege': typeof AuthenticatedAdminPersonalAntraegeRoute
  '/admin/pos-renner-penner': typeof AuthenticatedAdminPosRennerPennerRoute
  '/admin/pos-stundenbericht': typeof AuthenticatedAdminPosStundenberichtRoute
  '/admin/pos-verkauf': typeof AuthenticatedAdminPosVerkaufRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRouteWithChildren
  '/admin/standortzeiten': typeof AuthenticatedAdminStandortzeitenRoute
  '/admin/statistik': typeof AuthenticatedAdminStatistikRoute
  '/admin/trinkgeld-rest': typeof AuthenticatedAdminTrinkgeldRestRoute
  '/admin/urlaub': typeof AuthenticatedAdminUrlaubRoute
  '/admin/verkaufsartikel': typeof AuthenticatedAdminVerkaufsartikelRoute
  '/admin/wein': typeof AuthenticatedAdminWeinRoute
  '/admin/wein-quiz': typeof AuthenticatedAdminWeinQuizRoute
  '/admin/zeit-uebersicht': typeof AuthenticatedAdminZeitUebersichtRoute
  '/zeit/abrechnung': typeof AuthenticatedZeitAbrechnungRoute
  '/zeit/aufgaben': typeof AuthenticatedZeitAufgabenRoute
  '/zeit/kalender': typeof AuthenticatedZeitKalenderRoute
  '/zeit/schichten': typeof AuthenticatedZeitSchichtenRoute
  '/zeit/stempeln': typeof AuthenticatedZeitStempelnRoute
  '/zeit/stunden': typeof AuthenticatedZeitStundenRoute
  '/zeit/tausch': typeof AuthenticatedZeitTauschRoute
  '/zeit/urlaub': typeof AuthenticatedZeitUrlaubRoute
  '/zeit/wuensche': typeof AuthenticatedZeitWuenscheRoute
  '/api/export/download': typeof ApiExportDownloadRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/zeit/': typeof AuthenticatedZeitIndexRoute
  '/admin/bestellung/bestellungen': typeof AuthenticatedAdminBestellungBestellungenRoute
  '/admin/bestellung/inventur': typeof AuthenticatedAdminBestellungInventurRoute
  '/admin/bestellung/lieferanten': typeof AuthenticatedAdminBestellungLieferantenRoute
  '/admin/bestellung/unzugeordnet': typeof AuthenticatedAdminBestellungUnzugeordnetRoute
  '/admin/einstellungen/easyorder-verwaltung': typeof AuthenticatedAdminEinstellungenEasyorderVerwaltungRoute
  '/admin/einstellungen/veranstaltungen': typeof AuthenticatedAdminEinstellungenVeranstaltungenRoute
  '/admin/staff/$staffId': typeof AuthenticatedAdminStaffStaffIdRoute
  '/admin/staff/new': typeof AuthenticatedAdminStaffNewRoute
  '/api/public/bank/sync-spicery': typeof ApiPublicBankSyncSpiceryRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/display/$locationId': typeof ApiPublicDisplayLocationIdRoute
  '/api/public/mailersend/webhook': typeof ApiPublicMailersendWebhookRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/trmnl-dienstplan/$token': typeof ApiPublicTrmnlDienstplanTokenRoute
  '/api/public/trmnl-planungstafel/$token': typeof ApiPublicTrmnlPlanungstafelTokenRoute
  '/api/public/trmnl-tasks/$token': typeof ApiPublicTrmnlTasksTokenRoute
  '/api/public/weather/sync': typeof ApiPublicWeatherSyncRoute
  '/admin/bestellung/': typeof AuthenticatedAdminBestellungIndexRoute
  '/admin/einstellungen/': typeof AuthenticatedAdminEinstellungenIndexRoute
  '/admin/staff/': typeof AuthenticatedAdminStaffIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/easyorder': typeof AuthenticatedEasyorderRoute
  '/lohn': typeof AuthenticatedLohnRoute
  '/passwort-aendern': typeof AuthenticatedPasswortAendernRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/display/$locationId': typeof DisplayLocationIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/aufgaben': typeof AuthenticatedAdminAufgabenRoute
  '/admin/aufgaben-display': typeof AuthenticatedAdminAufgabenDisplayRoute
  '/admin/bankkonto': typeof AuthenticatedAdminBankkontoRoute
  '/admin/bilanz': typeof AuthenticatedAdminBilanzRoute
  '/admin/bwa': typeof AuthenticatedAdminBwaRoute
  '/admin/config-check': typeof AuthenticatedAdminConfigCheckRoute
  '/admin/dienstplan': typeof AuthenticatedAdminDienstplanRoute
  '/admin/dokumente': typeof AuthenticatedAdminDokumenteRoute
  '/admin/frag-coco': typeof AuthenticatedAdminFragCocoRoute
  '/admin/impersonate': typeof AuthenticatedAdminImpersonateRoute
  '/admin/import-zuordnungen': typeof AuthenticatedAdminImportZuordnungenRoute
  '/admin/kasse': typeof AuthenticatedAdminKasseRoute
  '/admin/kasse-saldo': typeof AuthenticatedAdminKasseSaldoRoute
  '/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/admin/lohn-verteilung': typeof AuthenticatedAdminLohnVerteilungRoute
  '/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/admin/personal-antraege': typeof AuthenticatedAdminPersonalAntraegeRoute
  '/admin/pos-renner-penner': typeof AuthenticatedAdminPosRennerPennerRoute
  '/admin/pos-stundenbericht': typeof AuthenticatedAdminPosStundenberichtRoute
  '/admin/pos-verkauf': typeof AuthenticatedAdminPosVerkaufRoute
  '/admin/standortzeiten': typeof AuthenticatedAdminStandortzeitenRoute
  '/admin/statistik': typeof AuthenticatedAdminStatistikRoute
  '/admin/trinkgeld-rest': typeof AuthenticatedAdminTrinkgeldRestRoute
  '/admin/urlaub': typeof AuthenticatedAdminUrlaubRoute
  '/admin/verkaufsartikel': typeof AuthenticatedAdminVerkaufsartikelRoute
  '/admin/wein': typeof AuthenticatedAdminWeinRoute
  '/admin/wein-quiz': typeof AuthenticatedAdminWeinQuizRoute
  '/admin/zeit-uebersicht': typeof AuthenticatedAdminZeitUebersichtRoute
  '/zeit/abrechnung': typeof AuthenticatedZeitAbrechnungRoute
  '/zeit/aufgaben': typeof AuthenticatedZeitAufgabenRoute
  '/zeit/kalender': typeof AuthenticatedZeitKalenderRoute
  '/zeit/schichten': typeof AuthenticatedZeitSchichtenRoute
  '/zeit/stempeln': typeof AuthenticatedZeitStempelnRoute
  '/zeit/stunden': typeof AuthenticatedZeitStundenRoute
  '/zeit/tausch': typeof AuthenticatedZeitTauschRoute
  '/zeit/urlaub': typeof AuthenticatedZeitUrlaubRoute
  '/zeit/wuensche': typeof AuthenticatedZeitWuenscheRoute
  '/api/export/download': typeof ApiExportDownloadRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/zeit': typeof AuthenticatedZeitIndexRoute
  '/admin/bestellung/bestellungen': typeof AuthenticatedAdminBestellungBestellungenRoute
  '/admin/bestellung/inventur': typeof AuthenticatedAdminBestellungInventurRoute
  '/admin/bestellung/lieferanten': typeof AuthenticatedAdminBestellungLieferantenRoute
  '/admin/bestellung/unzugeordnet': typeof AuthenticatedAdminBestellungUnzugeordnetRoute
  '/admin/einstellungen/easyorder-verwaltung': typeof AuthenticatedAdminEinstellungenEasyorderVerwaltungRoute
  '/admin/einstellungen/veranstaltungen': typeof AuthenticatedAdminEinstellungenVeranstaltungenRoute
  '/admin/staff/$staffId': typeof AuthenticatedAdminStaffStaffIdRoute
  '/admin/staff/new': typeof AuthenticatedAdminStaffNewRoute
  '/api/public/bank/sync-spicery': typeof ApiPublicBankSyncSpiceryRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/display/$locationId': typeof ApiPublicDisplayLocationIdRoute
  '/api/public/mailersend/webhook': typeof ApiPublicMailersendWebhookRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/trmnl-dienstplan/$token': typeof ApiPublicTrmnlDienstplanTokenRoute
  '/api/public/trmnl-planungstafel/$token': typeof ApiPublicTrmnlPlanungstafelTokenRoute
  '/api/public/trmnl-tasks/$token': typeof ApiPublicTrmnlTasksTokenRoute
  '/api/public/weather/sync': typeof ApiPublicWeatherSyncRoute
  '/admin/bestellung': typeof AuthenticatedAdminBestellungIndexRoute
  '/admin/einstellungen': typeof AuthenticatedAdminEinstellungenIndexRoute
  '/admin/staff': typeof AuthenticatedAdminStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/easyorder': typeof AuthenticatedEasyorderRoute
  '/_authenticated/lohn': typeof AuthenticatedLohnRoute
  '/_authenticated/passwort-aendern': typeof AuthenticatedPasswortAendernRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/display/$locationId': typeof DisplayLocationIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/aufgaben': typeof AuthenticatedAdminAufgabenRoute
  '/_authenticated/admin/aufgaben-display': typeof AuthenticatedAdminAufgabenDisplayRoute
  '/_authenticated/admin/bankkonto': typeof AuthenticatedAdminBankkontoRoute
  '/_authenticated/admin/bestellung': typeof AuthenticatedAdminBestellungRouteWithChildren
  '/_authenticated/admin/bilanz': typeof AuthenticatedAdminBilanzRoute
  '/_authenticated/admin/bwa': typeof AuthenticatedAdminBwaRoute
  '/_authenticated/admin/config-check': typeof AuthenticatedAdminConfigCheckRoute
  '/_authenticated/admin/dienstplan': typeof AuthenticatedAdminDienstplanRoute
  '/_authenticated/admin/dokumente': typeof AuthenticatedAdminDokumenteRoute
  '/_authenticated/admin/einstellungen': typeof AuthenticatedAdminEinstellungenRouteWithChildren
  '/_authenticated/admin/frag-coco': typeof AuthenticatedAdminFragCocoRoute
  '/_authenticated/admin/impersonate': typeof AuthenticatedAdminImpersonateRoute
  '/_authenticated/admin/import-zuordnungen': typeof AuthenticatedAdminImportZuordnungenRoute
  '/_authenticated/admin/kasse': typeof AuthenticatedAdminKasseRoute
  '/_authenticated/admin/kasse-saldo': typeof AuthenticatedAdminKasseSaldoRoute
  '/_authenticated/admin/locations': typeof AuthenticatedAdminLocationsRoute
  '/_authenticated/admin/lohn-verteilung': typeof AuthenticatedAdminLohnVerteilungRoute
  '/_authenticated/admin/migration': typeof AuthenticatedAdminMigrationRoute
  '/_authenticated/admin/personal-antraege': typeof AuthenticatedAdminPersonalAntraegeRoute
  '/_authenticated/admin/pos-renner-penner': typeof AuthenticatedAdminPosRennerPennerRoute
  '/_authenticated/admin/pos-stundenbericht': typeof AuthenticatedAdminPosStundenberichtRoute
  '/_authenticated/admin/pos-verkauf': typeof AuthenticatedAdminPosVerkaufRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRouteWithChildren
  '/_authenticated/admin/standortzeiten': typeof AuthenticatedAdminStandortzeitenRoute
  '/_authenticated/admin/statistik': typeof AuthenticatedAdminStatistikRoute
  '/_authenticated/admin/trinkgeld-rest': typeof AuthenticatedAdminTrinkgeldRestRoute
  '/_authenticated/admin/urlaub': typeof AuthenticatedAdminUrlaubRoute
  '/_authenticated/admin/verkaufsartikel': typeof AuthenticatedAdminVerkaufsartikelRoute
  '/_authenticated/admin/wein': typeof AuthenticatedAdminWeinRoute
  '/_authenticated/admin/wein-quiz': typeof AuthenticatedAdminWeinQuizRoute
  '/_authenticated/admin/zeit-uebersicht': typeof AuthenticatedAdminZeitUebersichtRoute
  '/_authenticated/zeit/abrechnung': typeof AuthenticatedZeitAbrechnungRoute
  '/_authenticated/zeit/aufgaben': typeof AuthenticatedZeitAufgabenRoute
  '/_authenticated/zeit/kalender': typeof AuthenticatedZeitKalenderRoute
  '/_authenticated/zeit/schichten': typeof AuthenticatedZeitSchichtenRoute
  '/_authenticated/zeit/stempeln': typeof AuthenticatedZeitStempelnRoute
  '/_authenticated/zeit/stunden': typeof AuthenticatedZeitStundenRoute
  '/_authenticated/zeit/tausch': typeof AuthenticatedZeitTauschRoute
  '/_authenticated/zeit/urlaub': typeof AuthenticatedZeitUrlaubRoute
  '/_authenticated/zeit/wuensche': typeof AuthenticatedZeitWuenscheRoute
  '/api/export/download': typeof ApiExportDownloadRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/zeit/': typeof AuthenticatedZeitIndexRoute
  '/_authenticated/admin/bestellung/bestellungen': typeof AuthenticatedAdminBestellungBestellungenRoute
  '/_authenticated/admin/bestellung/inventur': typeof AuthenticatedAdminBestellungInventurRoute
  '/_authenticated/admin/bestellung/lieferanten': typeof AuthenticatedAdminBestellungLieferantenRoute
  '/_authenticated/admin/bestellung/unzugeordnet': typeof AuthenticatedAdminBestellungUnzugeordnetRoute
  '/_authenticated/admin/einstellungen/easyorder-verwaltung': typeof AuthenticatedAdminEinstellungenEasyorderVerwaltungRoute
  '/_authenticated/admin/einstellungen/veranstaltungen': typeof AuthenticatedAdminEinstellungenVeranstaltungenRoute
  '/_authenticated/admin/staff/$staffId': typeof AuthenticatedAdminStaffStaffIdRoute
  '/_authenticated/admin/staff/new': typeof AuthenticatedAdminStaffNewRoute
  '/api/public/bank/sync-spicery': typeof ApiPublicBankSyncSpiceryRoute
  '/api/public/calendar/$token': typeof ApiPublicCalendarTokenRoute
  '/api/public/display/$locationId': typeof ApiPublicDisplayLocationIdRoute
  '/api/public/mailersend/webhook': typeof ApiPublicMailersendWebhookRoute
  '/api/public/telegram/daily-report': typeof ApiPublicTelegramDailyReportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/trmnl-dienstplan/$token': typeof ApiPublicTrmnlDienstplanTokenRoute
  '/api/public/trmnl-planungstafel/$token': typeof ApiPublicTrmnlPlanungstafelTokenRoute
  '/api/public/trmnl-tasks/$token': typeof ApiPublicTrmnlTasksTokenRoute
  '/api/public/weather/sync': typeof ApiPublicWeatherSyncRoute
  '/_authenticated/admin/bestellung/': typeof AuthenticatedAdminBestellungIndexRoute
  '/_authenticated/admin/einstellungen/': typeof AuthenticatedAdminEinstellungenIndexRoute
  '/_authenticated/admin/staff/': typeof AuthenticatedAdminStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/easyorder'
    | '/lohn'
    | '/passwort-aendern'
    | '/profil'
    | '/display/$locationId'
    | '/admin/aufgaben'
    | '/admin/aufgaben-display'
    | '/admin/bankkonto'
    | '/admin/bestellung'
    | '/admin/bilanz'
    | '/admin/bwa'
    | '/admin/config-check'
    | '/admin/dienstplan'
    | '/admin/dokumente'
    | '/admin/einstellungen'
    | '/admin/frag-coco'
    | '/admin/impersonate'
    | '/admin/import-zuordnungen'
    | '/admin/kasse'
    | '/admin/kasse-saldo'
    | '/admin/locations'
    | '/admin/lohn-verteilung'
    | '/admin/migration'
    | '/admin/personal-antraege'
    | '/admin/pos-renner-penner'
    | '/admin/pos-stundenbericht'
    | '/admin/pos-verkauf'
    | '/admin/staff'
    | '/admin/standortzeiten'
    | '/admin/statistik'
    | '/admin/trinkgeld-rest'
    | '/admin/urlaub'
    | '/admin/verkaufsartikel'
    | '/admin/wein'
    | '/admin/wein-quiz'
    | '/admin/zeit-uebersicht'
    | '/zeit/abrechnung'
    | '/zeit/aufgaben'
    | '/zeit/kalender'
    | '/zeit/schichten'
    | '/zeit/stempeln'
    | '/zeit/stunden'
    | '/zeit/tausch'
    | '/zeit/urlaub'
    | '/zeit/wuensche'
    | '/api/export/download'
    | '/admin/'
    | '/zeit/'
    | '/admin/bestellung/bestellungen'
    | '/admin/bestellung/inventur'
    | '/admin/bestellung/lieferanten'
    | '/admin/bestellung/unzugeordnet'
    | '/admin/einstellungen/easyorder-verwaltung'
    | '/admin/einstellungen/veranstaltungen'
    | '/admin/staff/$staffId'
    | '/admin/staff/new'
    | '/api/public/bank/sync-spicery'
    | '/api/public/calendar/$token'
    | '/api/public/display/$locationId'
    | '/api/public/mailersend/webhook'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/webhook'
    | '/api/public/trmnl-dienstplan/$token'
    | '/api/public/trmnl-planungstafel/$token'
    | '/api/public/trmnl-tasks/$token'
    | '/api/public/weather/sync'
    | '/admin/bestellung/'
    | '/admin/einstellungen/'
    | '/admin/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/easyorder'
    | '/lohn'
    | '/passwort-aendern'
    | '/profil'
    | '/display/$locationId'
    | '/'
    | '/admin/aufgaben'
    | '/admin/aufgaben-display'
    | '/admin/bankkonto'
    | '/admin/bilanz'
    | '/admin/bwa'
    | '/admin/config-check'
    | '/admin/dienstplan'
    | '/admin/dokumente'
    | '/admin/frag-coco'
    | '/admin/impersonate'
    | '/admin/import-zuordnungen'
    | '/admin/kasse'
    | '/admin/kasse-saldo'
    | '/admin/locations'
    | '/admin/lohn-verteilung'
    | '/admin/migration'
    | '/admin/personal-antraege'
    | '/admin/pos-renner-penner'
    | '/admin/pos-stundenbericht'
    | '/admin/pos-verkauf'
    | '/admin/standortzeiten'
    | '/admin/statistik'
    | '/admin/trinkgeld-rest'
    | '/admin/urlaub'
    | '/admin/verkaufsartikel'
    | '/admin/wein'
    | '/admin/wein-quiz'
    | '/admin/zeit-uebersicht'
    | '/zeit/abrechnung'
    | '/zeit/aufgaben'
    | '/zeit/kalender'
    | '/zeit/schichten'
    | '/zeit/stempeln'
    | '/zeit/stunden'
    | '/zeit/tausch'
    | '/zeit/urlaub'
    | '/zeit/wuensche'
    | '/api/export/download'
    | '/admin'
    | '/zeit'
    | '/admin/bestellung/bestellungen'
    | '/admin/bestellung/inventur'
    | '/admin/bestellung/lieferanten'
    | '/admin/bestellung/unzugeordnet'
    | '/admin/einstellungen/easyorder-verwaltung'
    | '/admin/einstellungen/veranstaltungen'
    | '/admin/staff/$staffId'
    | '/admin/staff/new'
    | '/api/public/bank/sync-spicery'
    | '/api/public/calendar/$token'
    | '/api/public/display/$locationId'
    | '/api/public/mailersend/webhook'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/webhook'
    | '/api/public/trmnl-dienstplan/$token'
    | '/api/public/trmnl-planungstafel/$token'
    | '/api/public/trmnl-tasks/$token'
    | '/api/public/weather/sync'
    | '/admin/bestellung'
    | '/admin/einstellungen'
    | '/admin/staff'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/easyorder'
    | '/_authenticated/lohn'
    | '/_authenticated/passwort-aendern'
    | '/_authenticated/profil'
    | '/display/$locationId'
    | '/_authenticated/'
    | '/_authenticated/admin/aufgaben'
    | '/_authenticated/admin/aufgaben-display'
    | '/_authenticated/admin/bankkonto'
    | '/_authenticated/admin/bestellung'
    | '/_authenticated/admin/bilanz'
    | '/_authenticated/admin/bwa'
    | '/_authenticated/admin/config-check'
    | '/_authenticated/admin/dienstplan'
    | '/_authenticated/admin/dokumente'
    | '/_authenticated/admin/einstellungen'
    | '/_authenticated/admin/frag-coco'
    | '/_authenticated/admin/impersonate'
    | '/_authenticated/admin/import-zuordnungen'
    | '/_authenticated/admin/kasse'
    | '/_authenticated/admin/kasse-saldo'
    | '/_authenticated/admin/locations'
    | '/_authenticated/admin/lohn-verteilung'
    | '/_authenticated/admin/migration'
    | '/_authenticated/admin/personal-antraege'
    | '/_authenticated/admin/pos-renner-penner'
    | '/_authenticated/admin/pos-stundenbericht'
    | '/_authenticated/admin/pos-verkauf'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/standortzeiten'
    | '/_authenticated/admin/statistik'
    | '/_authenticated/admin/trinkgeld-rest'
    | '/_authenticated/admin/urlaub'
    | '/_authenticated/admin/verkaufsartikel'
    | '/_authenticated/admin/wein'
    | '/_authenticated/admin/wein-quiz'
    | '/_authenticated/admin/zeit-uebersicht'
    | '/_authenticated/zeit/abrechnung'
    | '/_authenticated/zeit/aufgaben'
    | '/_authenticated/zeit/kalender'
    | '/_authenticated/zeit/schichten'
    | '/_authenticated/zeit/stempeln'
    | '/_authenticated/zeit/stunden'
    | '/_authenticated/zeit/tausch'
    | '/_authenticated/zeit/urlaub'
    | '/_authenticated/zeit/wuensche'
    | '/api/export/download'
    | '/_authenticated/admin/'
    | '/_authenticated/zeit/'
    | '/_authenticated/admin/bestellung/bestellungen'
    | '/_authenticated/admin/bestellung/inventur'
    | '/_authenticated/admin/bestellung/lieferanten'
    | '/_authenticated/admin/bestellung/unzugeordnet'
    | '/_authenticated/admin/einstellungen/easyorder-verwaltung'
    | '/_authenticated/admin/einstellungen/veranstaltungen'
    | '/_authenticated/admin/staff/$staffId'
    | '/_authenticated/admin/staff/new'
    | '/api/public/bank/sync-spicery'
    | '/api/public/calendar/$token'
    | '/api/public/display/$locationId'
    | '/api/public/mailersend/webhook'
    | '/api/public/telegram/daily-report'
    | '/api/public/telegram/webhook'
    | '/api/public/trmnl-dienstplan/$token'
    | '/api/public/trmnl-planungstafel/$token'
    | '/api/public/trmnl-tasks/$token'
    | '/api/public/weather/sync'
    | '/_authenticated/admin/bestellung/'
    | '/_authenticated/admin/einstellungen/'
    | '/_authenticated/admin/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DisplayLocationIdRoute: typeof DisplayLocationIdRoute
  ApiExportDownloadRoute: typeof ApiExportDownloadRoute
  ApiPublicBankSyncSpiceryRoute: typeof ApiPublicBankSyncSpiceryRoute
  ApiPublicCalendarTokenRoute: typeof ApiPublicCalendarTokenRoute
  ApiPublicDisplayLocationIdRoute: typeof ApiPublicDisplayLocationIdRoute
  ApiPublicMailersendWebhookRoute: typeof ApiPublicMailersendWebhookRoute
  ApiPublicTelegramDailyReportRoute: typeof ApiPublicTelegramDailyReportRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicTrmnlDienstplanTokenRoute: typeof ApiPublicTrmnlDienstplanTokenRoute
  ApiPublicTrmnlPlanungstafelTokenRoute: typeof ApiPublicTrmnlPlanungstafelTokenRoute
  ApiPublicTrmnlTasksTokenRoute: typeof ApiPublicTrmnlTasksTokenRoute
  ApiPublicWeatherSyncRoute: typeof ApiPublicWeatherSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/easyorder': {
      id: '/_authenticated/easyorder'
      path: '/easyorder'
      fullPath: '/easyorder'
      preLoaderRoute: typeof AuthenticatedEasyorderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lohn': {
      id: '/_authenticated/lohn'
      path: '/lohn'
      fullPath: '/lohn'
      preLoaderRoute: typeof AuthenticatedLohnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passwort-aendern': {
      id: '/_authenticated/passwort-aendern'
      path: '/passwort-aendern'
      fullPath: '/passwort-aendern'
      preLoaderRoute: typeof AuthenticatedPasswortAendernRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/display/$locationId': {
      id: '/display/$locationId'
      path: '/display/$locationId'
      fullPath: '/display/$locationId'
      preLoaderRoute: typeof DisplayLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/aufgaben': {
      id: '/_authenticated/admin/aufgaben'
      path: '/aufgaben'
      fullPath: '/admin/aufgaben'
      preLoaderRoute: typeof AuthenticatedAdminAufgabenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/aufgaben-display': {
      id: '/_authenticated/admin/aufgaben-display'
      path: '/aufgaben-display'
      fullPath: '/admin/aufgaben-display'
      preLoaderRoute: typeof AuthenticatedAdminAufgabenDisplayRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bankkonto': {
      id: '/_authenticated/admin/bankkonto'
      path: '/bankkonto'
      fullPath: '/admin/bankkonto'
      preLoaderRoute: typeof AuthenticatedAdminBankkontoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bestellung': {
      id: '/_authenticated/admin/bestellung'
      path: '/bestellung'
      fullPath: '/admin/bestellung'
      preLoaderRoute: typeof AuthenticatedAdminBestellungRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bilanz': {
      id: '/_authenticated/admin/bilanz'
      path: '/bilanz'
      fullPath: '/admin/bilanz'
      preLoaderRoute: typeof AuthenticatedAdminBilanzRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bwa': {
      id: '/_authenticated/admin/bwa'
      path: '/bwa'
      fullPath: '/admin/bwa'
      preLoaderRoute: typeof AuthenticatedAdminBwaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/config-check': {
      id: '/_authenticated/admin/config-check'
      path: '/config-check'
      fullPath: '/admin/config-check'
      preLoaderRoute: typeof AuthenticatedAdminConfigCheckRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dienstplan': {
      id: '/_authenticated/admin/dienstplan'
      path: '/dienstplan'
      fullPath: '/admin/dienstplan'
      preLoaderRoute: typeof AuthenticatedAdminDienstplanRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dokumente': {
      id: '/_authenticated/admin/dokumente'
      path: '/dokumente'
      fullPath: '/admin/dokumente'
      preLoaderRoute: typeof AuthenticatedAdminDokumenteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/einstellungen': {
      id: '/_authenticated/admin/einstellungen'
      path: '/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AuthenticatedAdminEinstellungenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/frag-coco': {
      id: '/_authenticated/admin/frag-coco'
      path: '/frag-coco'
      fullPath: '/admin/frag-coco'
      preLoaderRoute: typeof AuthenticatedAdminFragCocoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/impersonate': {
      id: '/_authenticated/admin/impersonate'
      path: '/impersonate'
      fullPath: '/admin/impersonate'
      preLoaderRoute: typeof AuthenticatedAdminImpersonateRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/import-zuordnungen': {
      id: '/_authenticated/admin/import-zuordnungen'
      path: '/import-zuordnungen'
      fullPath: '/admin/import-zuordnungen'
      preLoaderRoute: typeof AuthenticatedAdminImportZuordnungenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kasse': {
      id: '/_authenticated/admin/kasse'
      path: '/kasse'
      fullPath: '/admin/kasse'
      preLoaderRoute: typeof AuthenticatedAdminKasseRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/kasse-saldo': {
      id: '/_authenticated/admin/kasse-saldo'
      path: '/kasse-saldo'
      fullPath: '/admin/kasse-saldo'
      preLoaderRoute: typeof AuthenticatedAdminKasseSaldoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/locations': {
      id: '/_authenticated/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AuthenticatedAdminLocationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lohn-verteilung': {
      id: '/_authenticated/admin/lohn-verteilung'
      path: '/lohn-verteilung'
      fullPath: '/admin/lohn-verteilung'
      preLoaderRoute: typeof AuthenticatedAdminLohnVerteilungRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/migration': {
      id: '/_authenticated/admin/migration'
      path: '/migration'
      fullPath: '/admin/migration'
      preLoaderRoute: typeof AuthenticatedAdminMigrationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/personal-antraege': {
      id: '/_authenticated/admin/personal-antraege'
      path: '/personal-antraege'
      fullPath: '/admin/personal-antraege'
      preLoaderRoute: typeof AuthenticatedAdminPersonalAntraegeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pos-renner-penner': {
      id: '/_authenticated/admin/pos-renner-penner'
      path: '/pos-renner-penner'
      fullPath: '/admin/pos-renner-penner'
      preLoaderRoute: typeof AuthenticatedAdminPosRennerPennerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pos-stundenbericht': {
      id: '/_authenticated/admin/pos-stundenbericht'
      path: '/pos-stundenbericht'
      fullPath: '/admin/pos-stundenbericht'
      preLoaderRoute: typeof AuthenticatedAdminPosStundenberichtRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pos-verkauf': {
      id: '/_authenticated/admin/pos-verkauf'
      path: '/pos-verkauf'
      fullPath: '/admin/pos-verkauf'
      preLoaderRoute: typeof AuthenticatedAdminPosVerkaufRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/standortzeiten': {
      id: '/_authenticated/admin/standortzeiten'
      path: '/standortzeiten'
      fullPath: '/admin/standortzeiten'
      preLoaderRoute: typeof AuthenticatedAdminStandortzeitenRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/statistik': {
      id: '/_authenticated/admin/statistik'
      path: '/statistik'
      fullPath: '/admin/statistik'
      preLoaderRoute: typeof AuthenticatedAdminStatistikRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/trinkgeld-rest': {
      id: '/_authenticated/admin/trinkgeld-rest'
      path: '/trinkgeld-rest'
      fullPath: '/admin/trinkgeld-rest'
      preLoaderRoute: typeof AuthenticatedAdminTrinkgeldRestRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/urlaub': {
      id: '/_authenticated/admin/urlaub'
      path: '/urlaub'
      fullPath: '/admin/urlaub'
      preLoaderRoute: typeof AuthenticatedAdminUrlaubRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/verkaufsartikel': {
      id: '/_authenticated/admin/verkaufsartikel'
      path: '/verkaufsartikel'
      fullPath: '/admin/verkaufsartikel'
      preLoaderRoute: typeof AuthenticatedAdminVerkaufsartikelRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/wein': {
      id: '/_authenticated/admin/wein'
      path: '/wein'
      fullPath: '/admin/wein'
      preLoaderRoute: typeof AuthenticatedAdminWeinRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/wein-quiz': {
      id: '/_authenticated/admin/wein-quiz'
      path: '/wein-quiz'
      fullPath: '/admin/wein-quiz'
      preLoaderRoute: typeof AuthenticatedAdminWeinQuizRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/zeit-uebersicht': {
      id: '/_authenticated/admin/zeit-uebersicht'
      path: '/zeit-uebersicht'
      fullPath: '/admin/zeit-uebersicht'
      preLoaderRoute: typeof AuthenticatedAdminZeitUebersichtRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/zeit/': {
      id: '/_authenticated/zeit/'
      path: '/zeit'
      fullPath: '/zeit/'
      preLoaderRoute: typeof AuthenticatedZeitIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/abrechnung': {
      id: '/_authenticated/zeit/abrechnung'
      path: '/zeit/abrechnung'
      fullPath: '/zeit/abrechnung'
      preLoaderRoute: typeof AuthenticatedZeitAbrechnungRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/aufgaben': {
      id: '/_authenticated/zeit/aufgaben'
      path: '/zeit/aufgaben'
      fullPath: '/zeit/aufgaben'
      preLoaderRoute: typeof AuthenticatedZeitAufgabenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/kalender': {
      id: '/_authenticated/zeit/kalender'
      path: '/zeit/kalender'
      fullPath: '/zeit/kalender'
      preLoaderRoute: typeof AuthenticatedZeitKalenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/schichten': {
      id: '/_authenticated/zeit/schichten'
      path: '/zeit/schichten'
      fullPath: '/zeit/schichten'
      preLoaderRoute: typeof AuthenticatedZeitSchichtenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/stempeln': {
      id: '/_authenticated/zeit/stempeln'
      path: '/zeit/stempeln'
      fullPath: '/zeit/stempeln'
      preLoaderRoute: typeof AuthenticatedZeitStempelnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/stunden': {
      id: '/_authenticated/zeit/stunden'
      path: '/zeit/stunden'
      fullPath: '/zeit/stunden'
      preLoaderRoute: typeof AuthenticatedZeitStundenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/tausch': {
      id: '/_authenticated/zeit/tausch'
      path: '/zeit/tausch'
      fullPath: '/zeit/tausch'
      preLoaderRoute: typeof AuthenticatedZeitTauschRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/urlaub': {
      id: '/_authenticated/zeit/urlaub'
      path: '/zeit/urlaub'
      fullPath: '/zeit/urlaub'
      preLoaderRoute: typeof AuthenticatedZeitUrlaubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zeit/wuensche': {
      id: '/_authenticated/zeit/wuensche'
      path: '/zeit/wuensche'
      fullPath: '/zeit/wuensche'
      preLoaderRoute: typeof AuthenticatedZeitWuenscheRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/export/download': {
      id: '/api/export/download'
      path: '/api/export/download'
      fullPath: '/api/export/download'
      preLoaderRoute: typeof ApiExportDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/bestellung/': {
      id: '/_authenticated/admin/bestellung/'
      path: '/'
      fullPath: '/admin/bestellung/'
      preLoaderRoute: typeof AuthenticatedAdminBestellungIndexRouteImport
      parentRoute: typeof AuthenticatedAdminBestellungRoute
    }
    '/_authenticated/admin/bestellung/bestellungen': {
      id: '/_authenticated/admin/bestellung/bestellungen'
      path: '/bestellungen'
      fullPath: '/admin/bestellung/bestellungen'
      preLoaderRoute: typeof AuthenticatedAdminBestellungBestellungenRouteImport
      parentRoute: typeof AuthenticatedAdminBestellungRoute
    }
    '/_authenticated/admin/bestellung/inventur': {
      id: '/_authenticated/admin/bestellung/inventur'
      path: '/inventur'
      fullPath: '/admin/bestellung/inventur'
      preLoaderRoute: typeof AuthenticatedAdminBestellungInventurRouteImport
      parentRoute: typeof AuthenticatedAdminBestellungRoute
    }
    '/_authenticated/admin/bestellung/lieferanten': {
      id: '/_authenticated/admin/bestellung/lieferanten'
      path: '/lieferanten'
      fullPath: '/admin/bestellung/lieferanten'
      preLoaderRoute: typeof AuthenticatedAdminBestellungLieferantenRouteImport
      parentRoute: typeof AuthenticatedAdminBestellungRoute
    }
    '/_authenticated/admin/bestellung/unzugeordnet': {
      id: '/_authenticated/admin/bestellung/unzugeordnet'
      path: '/unzugeordnet'
      fullPath: '/admin/bestellung/unzugeordnet'
      preLoaderRoute: typeof AuthenticatedAdminBestellungUnzugeordnetRouteImport
      parentRoute: typeof AuthenticatedAdminBestellungRoute
    }
    '/_authenticated/admin/einstellungen/': {
      id: '/_authenticated/admin/einstellungen/'
      path: '/'
      fullPath: '/admin/einstellungen/'
      preLoaderRoute: typeof AuthenticatedAdminEinstellungenIndexRouteImport
      parentRoute: typeof AuthenticatedAdminEinstellungenRoute
    }
    '/_authenticated/admin/einstellungen/easyorder-verwaltung': {
      id: '/_authenticated/admin/einstellungen/easyorder-verwaltung'
      path: '/easyorder-verwaltung'
      fullPath: '/admin/einstellungen/easyorder-verwaltung'
      preLoaderRoute: typeof AuthenticatedAdminEinstellungenEasyorderVerwaltungRouteImport
      parentRoute: typeof AuthenticatedAdminEinstellungenRoute
    }
    '/_authenticated/admin/einstellungen/veranstaltungen': {
      id: '/_authenticated/admin/einstellungen/veranstaltungen'
      path: '/veranstaltungen'
      fullPath: '/admin/einstellungen/veranstaltungen'
      preLoaderRoute: typeof AuthenticatedAdminEinstellungenVeranstaltungenRouteImport
      parentRoute: typeof AuthenticatedAdminEinstellungenRoute
    }
    '/_authenticated/admin/staff/': {
      id: '/_authenticated/admin/staff/'
      path: '/'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AuthenticatedAdminStaffIndexRouteImport
      parentRoute: typeof AuthenticatedAdminStaffRoute
    }
    '/_authenticated/admin/staff/$staffId': {
      id: '/_authenticated/admin/staff/$staffId'
      path: '/$staffId'
      fullPath: '/admin/staff/$staffId'
      preLoaderRoute: typeof AuthenticatedAdminStaffStaffIdRouteImport
      parentRoute: typeof AuthenticatedAdminStaffRoute
    }
    '/_authenticated/admin/staff/new': {
      id: '/_authenticated/admin/staff/new'
      path: '/new'
      fullPath: '/admin/staff/new'
      preLoaderRoute: typeof AuthenticatedAdminStaffNewRouteImport
      parentRoute: typeof AuthenticatedAdminStaffRoute
    }
    '/api/public/bank/sync-spicery': {
      id: '/api/public/bank/sync-spicery'
      path: '/api/public/bank/sync-spicery'
      fullPath: '/api/public/bank/sync-spicery'
      preLoaderRoute: typeof ApiPublicBankSyncSpiceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calendar/$token': {
      id: '/api/public/calendar/$token'
      path: '/api/public/calendar/$token'
      fullPath: '/api/public/calendar/$token'
      preLoaderRoute: typeof ApiPublicCalendarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/display/$locationId': {
      id: '/api/public/display/$locationId'
      path: '/api/public/display/$locationId'
      fullPath: '/api/public/display/$locationId'
      preLoaderRoute: typeof ApiPublicDisplayLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mailersend/webhook': {
      id: '/api/public/mailersend/webhook'
      path: '/api/public/mailersend/webhook'
      fullPath: '/api/public/mailersend/webhook'
      preLoaderRoute: typeof ApiPublicMailersendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/daily-report': {
      id: '/api/public/telegram/daily-report'
      path: '/api/public/telegram/daily-report'
      fullPath: '/api/public/telegram/daily-report'
      preLoaderRoute: typeof ApiPublicTelegramDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trmnl-dienstplan/$token': {
      id: '/api/public/trmnl-dienstplan/$token'
      path: '/api/public/trmnl-dienstplan/$token'
      fullPath: '/api/public/trmnl-dienstplan/$token'
      preLoaderRoute: typeof ApiPublicTrmnlDienstplanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trmnl-planungstafel/$token': {
      id: '/api/public/trmnl-planungstafel/$token'
      path: '/api/public/trmnl-planungstafel/$token'
      fullPath: '/api/public/trmnl-planungstafel/$token'
      preLoaderRoute: typeof ApiPublicTrmnlPlanungstafelTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trmnl-tasks/$token': {
      id: '/api/public/trmnl-tasks/$token'
      path: '/api/public/trmnl-tasks/$token'
      fullPath: '/api/public/trmnl-tasks/$token'
      preLoaderRoute: typeof ApiPublicTrmnlTasksTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weather/sync': {
      id: '/api/public/weather/sync'
      path: '/api/public/weather/sync'
      fullPath: '/api/public/weather/sync'
      preLoaderRoute: typeof ApiPublicWeatherSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminBestellungRouteChildren {
  AuthenticatedAdminBestellungBestellungenRoute: typeof AuthenticatedAdminBestellungBestellungenRoute
  AuthenticatedAdminBestellungInventurRoute: typeof AuthenticatedAdminBestellungInventurRoute
  AuthenticatedAdminBestellungLieferantenRoute: typeof AuthenticatedAdminBestellungLieferantenRoute
  AuthenticatedAdminBestellungUnzugeordnetRoute: typeof AuthenticatedAdminBestellungUnzugeordnetRoute
  AuthenticatedAdminBestellungIndexRoute: typeof AuthenticatedAdminBestellungIndexRoute
}

const AuthenticatedAdminBestellungRouteChildren: AuthenticatedAdminBestellungRouteChildren =
  {
    AuthenticatedAdminBestellungBestellungenRoute:
      AuthenticatedAdminBestellungBestellungenRoute,
    AuthenticatedAdminBestellungInventurRoute:
      AuthenticatedAdminBestellungInventurRoute,
    AuthenticatedAdminBestellungLieferantenRoute:
      AuthenticatedAdminBestellungLieferantenRoute,
    AuthenticatedAdminBestellungUnzugeordnetRoute:
      AuthenticatedAdminBestellungUnzugeordnetRoute,
    AuthenticatedAdminBestellungIndexRoute:
      AuthenticatedAdminBestellungIndexRoute,
  }

const AuthenticatedAdminBestellungRouteWithChildren =
  AuthenticatedAdminBestellungRoute._addFileChildren(
    AuthenticatedAdminBestellungRouteChildren,
  )

interface AuthenticatedAdminEinstellungenRouteChildren {
  AuthenticatedAdminEinstellungenEasyorderVerwaltungRoute: typeof AuthenticatedAdminEinstellungenEasyorderVerwaltungRoute
  AuthenticatedAdminEinstellungenVeranstaltungenRoute: typeof AuthenticatedAdminEinstellungenVeranstaltungenRoute
  AuthenticatedAdminEinstellungenIndexRoute: typeof AuthenticatedAdminEinstellungenIndexRoute
}

const AuthenticatedAdminEinstellungenRouteChildren: AuthenticatedAdminEinstellungenRouteChildren =
  {
    AuthenticatedAdminEinstellungenEasyorderVerwaltungRoute:
      AuthenticatedAdminEinstellungenEasyorderVerwaltungRoute,
    AuthenticatedAdminEinstellungenVeranstaltungenRoute:
      AuthenticatedAdminEinstellungenVeranstaltungenRoute,
    AuthenticatedAdminEinstellungenIndexRoute:
      AuthenticatedAdminEinstellungenIndexRoute,
  }

const AuthenticatedAdminEinstellungenRouteWithChildren =
  AuthenticatedAdminEinstellungenRoute._addFileChildren(
    AuthenticatedAdminEinstellungenRouteChildren,
  )

interface AuthenticatedAdminStaffRouteChildren {
  AuthenticatedAdminStaffStaffIdRoute: typeof AuthenticatedAdminStaffStaffIdRoute
  AuthenticatedAdminStaffNewRoute: typeof AuthenticatedAdminStaffNewRoute
  AuthenticatedAdminStaffIndexRoute: typeof AuthenticatedAdminStaffIndexRoute
}

const AuthenticatedAdminStaffRouteChildren: AuthenticatedAdminStaffRouteChildren =
  {
    AuthenticatedAdminStaffStaffIdRoute: AuthenticatedAdminStaffStaffIdRoute,
    AuthenticatedAdminStaffNewRoute: AuthenticatedAdminStaffNewRoute,
    AuthenticatedAdminStaffIndexRoute: AuthenticatedAdminStaffIndexRoute,
  }

const AuthenticatedAdminStaffRouteWithChildren =
  AuthenticatedAdminStaffRoute._addFileChildren(
    AuthenticatedAdminStaffRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAufgabenRoute: typeof AuthenticatedAdminAufgabenRoute
  AuthenticatedAdminAufgabenDisplayRoute: typeof AuthenticatedAdminAufgabenDisplayRoute
  AuthenticatedAdminBankkontoRoute: typeof AuthenticatedAdminBankkontoRoute
  AuthenticatedAdminBestellungRoute: typeof AuthenticatedAdminBestellungRouteWithChildren
  AuthenticatedAdminBilanzRoute: typeof AuthenticatedAdminBilanzRoute
  AuthenticatedAdminBwaRoute: typeof AuthenticatedAdminBwaRoute
  AuthenticatedAdminConfigCheckRoute: typeof AuthenticatedAdminConfigCheckRoute
  AuthenticatedAdminDienstplanRoute: typeof AuthenticatedAdminDienstplanRoute
  AuthenticatedAdminDokumenteRoute: typeof AuthenticatedAdminDokumenteRoute
  AuthenticatedAdminEinstellungenRoute: typeof AuthenticatedAdminEinstellungenRouteWithChildren
  AuthenticatedAdminFragCocoRoute: typeof AuthenticatedAdminFragCocoRoute
  AuthenticatedAdminImpersonateRoute: typeof AuthenticatedAdminImpersonateRoute
  AuthenticatedAdminImportZuordnungenRoute: typeof AuthenticatedAdminImportZuordnungenRoute
  AuthenticatedAdminKasseRoute: typeof AuthenticatedAdminKasseRoute
  AuthenticatedAdminKasseSaldoRoute: typeof AuthenticatedAdminKasseSaldoRoute
  AuthenticatedAdminLocationsRoute: typeof AuthenticatedAdminLocationsRoute
  AuthenticatedAdminLohnVerteilungRoute: typeof AuthenticatedAdminLohnVerteilungRoute
  AuthenticatedAdminMigrationRoute: typeof AuthenticatedAdminMigrationRoute
  AuthenticatedAdminPersonalAntraegeRoute: typeof AuthenticatedAdminPersonalAntraegeRoute
  AuthenticatedAdminPosRennerPennerRoute: typeof AuthenticatedAdminPosRennerPennerRoute
  AuthenticatedAdminPosStundenberichtRoute: typeof AuthenticatedAdminPosStundenberichtRoute
  AuthenticatedAdminPosVerkaufRoute: typeof AuthenticatedAdminPosVerkaufRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRouteWithChildren
  AuthenticatedAdminStandortzeitenRoute: typeof AuthenticatedAdminStandortzeitenRoute
  AuthenticatedAdminStatistikRoute: typeof AuthenticatedAdminStatistikRoute
  AuthenticatedAdminTrinkgeldRestRoute: typeof AuthenticatedAdminTrinkgeldRestRoute
  AuthenticatedAdminUrlaubRoute: typeof AuthenticatedAdminUrlaubRoute
  AuthenticatedAdminVerkaufsartikelRoute: typeof AuthenticatedAdminVerkaufsartikelRoute
  AuthenticatedAdminWeinRoute: typeof AuthenticatedAdminWeinRoute
  AuthenticatedAdminWeinQuizRoute: typeof AuthenticatedAdminWeinQuizRoute
  AuthenticatedAdminZeitUebersichtRoute: typeof AuthenticatedAdminZeitUebersichtRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAufgabenRoute: AuthenticatedAdminAufgabenRoute,
    AuthenticatedAdminAufgabenDisplayRoute:
      AuthenticatedAdminAufgabenDisplayRoute,
    AuthenticatedAdminBankkontoRoute: AuthenticatedAdminBankkontoRoute,
    AuthenticatedAdminBestellungRoute:
      AuthenticatedAdminBestellungRouteWithChildren,
    AuthenticatedAdminBilanzRoute: AuthenticatedAdminBilanzRoute,
    AuthenticatedAdminBwaRoute: AuthenticatedAdminBwaRoute,
    AuthenticatedAdminConfigCheckRoute: AuthenticatedAdminConfigCheckRoute,
    AuthenticatedAdminDienstplanRoute: AuthenticatedAdminDienstplanRoute,
    AuthenticatedAdminDokumenteRoute: AuthenticatedAdminDokumenteRoute,
    AuthenticatedAdminEinstellungenRoute:
      AuthenticatedAdminEinstellungenRouteWithChildren,
    AuthenticatedAdminFragCocoRoute: AuthenticatedAdminFragCocoRoute,
    AuthenticatedAdminImpersonateRoute: AuthenticatedAdminImpersonateRoute,
    AuthenticatedAdminImportZuordnungenRoute:
      AuthenticatedAdminImportZuordnungenRoute,
    AuthenticatedAdminKasseRoute: AuthenticatedAdminKasseRoute,
    AuthenticatedAdminKasseSaldoRoute: AuthenticatedAdminKasseSaldoRoute,
    AuthenticatedAdminLocationsRoute: AuthenticatedAdminLocationsRoute,
    AuthenticatedAdminLohnVerteilungRoute:
      AuthenticatedAdminLohnVerteilungRoute,
    AuthenticatedAdminMigrationRoute: AuthenticatedAdminMigrationRoute,
    AuthenticatedAdminPersonalAntraegeRoute:
      AuthenticatedAdminPersonalAntraegeRoute,
    AuthenticatedAdminPosRennerPennerRoute:
      AuthenticatedAdminPosRennerPennerRoute,
    AuthenticatedAdminPosStundenberichtRoute:
      AuthenticatedAdminPosStundenberichtRoute,
    AuthenticatedAdminPosVerkaufRoute: AuthenticatedAdminPosVerkaufRoute,
    AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRouteWithChildren,
    AuthenticatedAdminStandortzeitenRoute:
      AuthenticatedAdminStandortzeitenRoute,
    AuthenticatedAdminStatistikRoute: AuthenticatedAdminStatistikRoute,
    AuthenticatedAdminTrinkgeldRestRoute: AuthenticatedAdminTrinkgeldRestRoute,
    AuthenticatedAdminUrlaubRoute: AuthenticatedAdminUrlaubRoute,
    AuthenticatedAdminVerkaufsartikelRoute:
      AuthenticatedAdminVerkaufsartikelRoute,
    AuthenticatedAdminWeinRoute: AuthenticatedAdminWeinRoute,
    AuthenticatedAdminWeinQuizRoute: AuthenticatedAdminWeinQuizRoute,
    AuthenticatedAdminZeitUebersichtRoute:
      AuthenticatedAdminZeitUebersichtRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedEasyorderRoute: typeof AuthenticatedEasyorderRoute
  AuthenticatedLohnRoute: typeof AuthenticatedLohnRoute
  AuthenticatedPasswortAendernRoute: typeof AuthenticatedPasswortAendernRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedZeitAbrechnungRoute: typeof AuthenticatedZeitAbrechnungRoute
  AuthenticatedZeitAufgabenRoute: typeof AuthenticatedZeitAufgabenRoute
  AuthenticatedZeitKalenderRoute: typeof AuthenticatedZeitKalenderRoute
  AuthenticatedZeitSchichtenRoute: typeof AuthenticatedZeitSchichtenRoute
  AuthenticatedZeitStempelnRoute: typeof AuthenticatedZeitStempelnRoute
  AuthenticatedZeitStundenRoute: typeof AuthenticatedZeitStundenRoute
  AuthenticatedZeitTauschRoute: typeof AuthenticatedZeitTauschRoute
  AuthenticatedZeitUrlaubRoute: typeof AuthenticatedZeitUrlaubRoute
  AuthenticatedZeitWuenscheRoute: typeof AuthenticatedZeitWuenscheRoute
  AuthenticatedZeitIndexRoute: typeof AuthenticatedZeitIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedEasyorderRoute: AuthenticatedEasyorderRoute,
  AuthenticatedLohnRoute: AuthenticatedLohnRoute,
  AuthenticatedPasswortAendernRoute: AuthenticatedPasswortAendernRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedZeitAbrechnungRoute: AuthenticatedZeitAbrechnungRoute,
  AuthenticatedZeitAufgabenRoute: AuthenticatedZeitAufgabenRoute,
  AuthenticatedZeitKalenderRoute: AuthenticatedZeitKalenderRoute,
  AuthenticatedZeitSchichtenRoute: AuthenticatedZeitSchichtenRoute,
  AuthenticatedZeitStempelnRoute: AuthenticatedZeitStempelnRoute,
  AuthenticatedZeitStundenRoute: AuthenticatedZeitStundenRoute,
  AuthenticatedZeitTauschRoute: AuthenticatedZeitTauschRoute,
  AuthenticatedZeitUrlaubRoute: AuthenticatedZeitUrlaubRoute,
  AuthenticatedZeitWuenscheRoute: AuthenticatedZeitWuenscheRoute,
  AuthenticatedZeitIndexRoute: AuthenticatedZeitIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DisplayLocationIdRoute: DisplayLocationIdRoute,
  ApiExportDownloadRoute: ApiExportDownloadRoute,
  ApiPublicBankSyncSpiceryRoute: ApiPublicBankSyncSpiceryRoute,
  ApiPublicCalendarTokenRoute: ApiPublicCalendarTokenRoute,
  ApiPublicDisplayLocationIdRoute: ApiPublicDisplayLocationIdRoute,
  ApiPublicMailersendWebhookRoute: ApiPublicMailersendWebhookRoute,
  ApiPublicTelegramDailyReportRoute: ApiPublicTelegramDailyReportRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicTrmnlDienstplanTokenRoute: ApiPublicTrmnlDienstplanTokenRoute,
  ApiPublicTrmnlPlanungstafelTokenRoute: ApiPublicTrmnlPlanungstafelTokenRoute,
  ApiPublicTrmnlTasksTokenRoute: ApiPublicTrmnlTasksTokenRoute,
  ApiPublicWeatherSyncRoute: ApiPublicWeatherSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
